### PR TITLE
Changed abs() to std::abs() for MSYS2 compat

### PR DESCRIPTION
**Pull request by jhendren**

### CODE REVIEW

**Comment by lindenbergresearch** [comment]
Shouldn't I commit the changes?

**Comment by jhendren** [comment]
Hi Patrick,

My apologies, I committed to upstream by mistake from my fork. I removed
the commit.

A little background: Currently I am getting compile errors when building
under Windows 10, using the standard build environment of MSYS2. GCC throws
an error on ReShaper.cpp and points to the line where abs() is used. The
cast of float to abs is ambiguous, as apparently under MSYS2 abs() is for
integers only. Changing to std::abs() allows the compiler to build as the
stdlib has overloaded methods that can deal with floats.

Anyway, I'm getting the same issue with Strum's Mental Modules, and I let
him know about it as well. Something either strange with my environment, or
possibly the MSYS2 system itself. I forked the repos of both your sources
so that I could build here.

Once again, sorry about the commit. Maybe check collaborator access and
lock down the repo so it doesn't happen with others?

Cheers,
Justin Hendren

**Comment by lindenbergresearch** [comment]
Hi Justin,

sorry for the late answer, I was a bit under stress that days. I will setup a win environment by myself when releasing my new modules, lets then see what happens when compiling. 

Thank you in advance,
Patrick

**Comment by jhendren** [comment]
Sure can. I'll see if I can't get one made for you this weekend.

**Comment by jhendren** [comment]
Hi Patrick,

I've compiled and uploaded the Windows build of your newest, v.0.0.5.182. 

You can find it here: https://github.com/jhendren/LRTRack/releases/tag/v0.0.5.182

Maybe soon I can automate this build for you. Looking at options :) 

I have tested this briefly and it appears to work fine. I'll delete the release once you get it copied over.

If you have any questions, please let me know.

-Justin

**Comment by jhendren** [comment]
Hi Patrick,

I've compiled and uploaded the Windows build of your newest, v.0.0.5.182.

You can find it here:
https://github.com/jhendren/LRTRack/releases/tag/v0.0.5.182

Maybe soon I can automate this build for you. Looking at options :)

I have tested this briefly and it appears to work fine. I'll delete the
release once you get it copied over.

If you have any questions, please let me know.

Justin Hendren

**Pull request closed without merging**
